language: node_js
cache: yarn
node_js:
  - 'lts/*'
env:
  POLL_FREQUENCY: 2147483647
script:
  - yarn build
  - yarn lint
  - yarn test
services:
  - docker
deploy:
  - provider: script
    script: ./deploy.sh $TRAVIS_BRANCH
    on:
      branch: master
  - provider: script
    script: ./deploy.sh $TRAVIS_TAG
    on:
      tags: true
